#!/usr/bin/env bash

url="$1"
protocol="${url%%:*}"
if [ -n "$protocol" ]; then
  domain="$(awk -F/ '{print $3}' <<< "$url")"
else
  domain="$(awk -F/ '{print $1}' <<< "$url")"
fi
paste="$(curl -sL "$url")"
if ! grep --color=auto -qE '<html|<!DOCTYPE' <<< "$paste"; then
  echo "$paste"
  return
fi
rawlink="$(
curl -sLN "$url" |
  perl -ne '
  m/raw|plain|show as text|download/i &&
  ! m/.zip/ &&
  m/href/i &&
  s|.*?href\s*=\s*["'\'']([^"'\'']+).*|\1|i &&
  print && exit'
)"
if [[ "${rawlink:0:4}" == 'http' ]]; then
  url="$rawlink"
else
  if [[ "${rawlink:0:1}" == '/' ]]; then
    url="$protocol://$domain$rawlink"
  else
    url="$protocol://$rawlink"
  fi
fi
[ -n "$rawlink" ] && curl -sL "$url" || echo curl -L "$url" \?
